Further changes for #28
getumbrel/umbrel-compose pull request #31
Opened 2020-06-26 06:55 UTC by mayankchhabra

2020-06-26 08:08 UTC, nolim1t commented
the tls options work for me

2020-06-26 08:14 UTC, mayankchhabra commented
Strange, it doesn't work for me at all on all 3 chains. Can you try on a fresh install?

2020-06-28 07:36 UTC, mayankchhabra commented
Can we merge this today? Want #28 to be merged before I work on the OTA updates

2020-06-29 02:23 UTC, nolim1t commented
Can we leave the torrc config alone.. the extra line isn't harming anything

2020-06-29 02:30 UTC, nolim1t commented
tlsautorefresh is enabled for me and works

2020-06-29 03:50 UTC, mayankchhabra commented
> Can we leave the torrc config alone.. the extra line isn't harming anything

Isn't hardcoding a Tor password a security risk? Plus is it even being used anywhere since a new password is generated on the device anyway? 

> tlsautorefresh is enabled for me and works
Ok then I'll uncomment it

2020-07-03 06:35 UTC, nolim1t requested changes
LGTM.. just a few things I'd like to keep off for now

2020-07-03 06:35 UTC, nolim1t commented on lnd/lnd.conf
> +; tlsautorefresh=1
Why comment this out? its a useful feature to have

2020-07-03 06:35 UTC, nolim1t commented on lnd/lnd.conf
> +; tlsextraip=10.11.1.2
Also regarding commenting this out too

2020-07-03 06:35 UTC, nolim1t commented on tor/torrc
> -HashedControlPassword 16:50A873DF18C00F4A6048BF1CEF7E7AA66478F0B5134DA4369D80657F26
Please keep this in for now. I'll remove it later

2020-07-03 06:35 UTC, nolim1t commented on lnd/lnd.conf
> +; tlsextraip=10.11.1.2
Can we keep this comment as it is?

2020-07-03 06:35 UTC, nolim1t commented on tor/torrc
> -HashedControlPassword 16:50A873DF18C00F4A6048BF1CEF7E7AA66478F0B5134DA4369D80657F26
Also this too. THanks.

Rest looks good otherwise

2020-07-03 10:09 UTC, nolim1t approved these changes

2020-07-03 10:10 UTC, merged

2020-07-03 10:10 UTC, nolim1t commented
Merged into draft branch. Thanks for the tor container too